appname = AUTH_MOCK_SERVER

########Deploy flag##############
#runmode prod or dev
runmode = prod
# 0: debug, stage. 1: release
DeployMode = "${DEPLOY_MODE||0}"

#########HTTP default bind all ip###################
EnableHTTP = "${SRV_HTTP_ENABLE||true}"
HTTPAddr = "${SRV_HTTP_ADDR||0.0.0.0}"
HTTPPort = "${SRV_HTTP_PORT||8892}"

copyrequestbody = true

####################WW Server URL###########################
api_server_url="https://console.stage.sandbox.authsec.io"
api_code="52VaVMa4mNmw6FbEQ"
api_secret="8Sgdm59CM1q5syMwkcZFwdMPh38"


